branch-defaults:
  api-integration:
    environment: my-apis-env
environment-defaults:
  my-apis-env:
    branch: null
    repository: null
global:
  application_name: my-apis
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.09 v2.2.0 running Python 2.7
  default_region: ap-southeast-2
  profile: eb-cli
  sc: git
